name: sports_zone
description: sports app using flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  animated_splash_screen: ^1.3.0
  introduction_screen: ^3.1.11
  shared_preferences: ^2.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.4
  lottie: ^2.5.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/google_fonts/
